import { StyleSheet, Dimensions } from 'react-native';
import Constants from 'expo-constants';

const statusBarHeight = Constants.statusBarHeight;
const screenWidth = Math.round(Dimensions.get('window').width);

// Colors
export const Colors = {
  primary: '#f06262',
  danger: '#dc3545',
  yellow: '#f2ec3f',
  white: '#fff',
  black: '#000',
  gray: '#A0A0A0',
  text: '#212529',
  border: '#dee2e6',
  disabled: '#eee',
};

const { primary, danger, yellow, white, text, border } = Colors;

export const styles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    padding: 25,
    paddingTop: statusBarHeight + 10,
    backgroundColor: white,
  },
  innerContainer: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
  },
  rowContainer: {
    width: '100%',
    height: 75,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pageTitle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 27,
    textAlign: 'center',
    fontWeight: 'bold',
    color: primary,
    padding: 10,
  },
  subTitle: {
    fontSize: 18,
    alignSelf: 'flex-start',
    letterSpacing: 1,
    fontWeight: 'bold',
    color: primary,
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 15,
    paddingLeft: 15,
  },
  paragraph: {
    fontSize: 17,
    fontFamily: 'Poppins-Medium',
    color: text,
  },
  pageLogo: {
    objectFit: 'contain',
    height: 40,
    width: 150,
  },
  languageButton: {
    paddingVertical: 2,
    paddingHorizontal: 25,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  welcomeImage: {
    objectFit: 'contain',
    width: screenWidth,
    height: screenWidth / 1.2,
    marginBottom: 20,
  },
  button: {
    width: '100%',
    height: 50,
    backgroundColor: primary,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  buttonText: {
    fontSize: 17,
    fontFamily: 'Poppins-Medium',
    color: white,
  },
  dropDownSelector: {
    width: '90%',
    minHeight: 50,
    marginBottom: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: 15,
    paddingLeft: 15,
  },
  dropDownArea: {
    position: 'absolute',
    zIndex: 1,
    top: 50,
    width: '90%',
    maxHeight: 300,
    borderRadius: 10,
    marginTop: 10,
    paddingBottom: 10,
    backgroundColor: white,
    elevation: 5,
  },
  dropDownItem: {
    width: '90%',
    minHeight: 70,
    borderRadius: 10,
    borderBottomWidth: 1,
    borderBottomColor: border,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: 15,
    paddingLeft: 15,
  },
  searchBar: {
    width: '90%',
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: border,
    marginTop: 20,
    marginBottom: 10,
    alignSelf: 'center',
    paddingRight: 15,
    paddingLeft: 15,
  },
  inputField: {
    position: 'relative',
    width: '90%',
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 20,
    paddingRight: 15,
    paddingLeft: 15,
  },
  rightIcon: {
    position: 'absolute',
    right: 15,
    top: 15,
  },
  errorMessage: {
    color: danger,
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 10,
    paddingRight: 20,
    paddingLeft: 20,
  },
  intervalOption: {
    height: 45,
    minWidth: 95,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: border,
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  proTag: {
    position: 'absolute',
    right: -17,
    top: 5,
    transform: [{ rotate: '25deg' }],
    paddingHorizontal: 10,
    backgroundColor: yellow,
    borderRadius: 10,
  },
  customIntervalInput: {
    height: 45,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: border,
    marginTop: 10,
    marginBottom: 10,
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  durationError: {
    position: 'absolute',
    bottom: -15,
    left: 20,
    color: Colors.danger,
  },
  dot: {
    width: screenWidth / 2,
    height: screenWidth / 2,
    borderRadius: screenWidth / 2,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  selected: {
    backgroundColor: primary,
  },
  /********* Marks ********/
  marksOuterContainer: {
    flex: 1,
    padding: 10,
    paddingBottom: 0,
    paddingTop: statusBarHeight + 10,
    backgroundColor: white,
  },
  marksHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  marksTableHeader: {
    height: 60,
    backgroundColor: Colors.primary,
  },
  marksTableHeaderText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    color: white,
    margin: 5,
  },
  marksRowText: {
    fontSize: 12,
    color: text,
    margin: 5,
  },
});
